root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/rawviewer-api ./cmd/rawviewer-api"
bin = "./tmp/rawviewer-api"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
exclude_regex = ["_test.go"]
delay = 300
stop_on_error = true

[log]
time = true
